
/**
* @name: MyCrudDao.java 
*
* @Copyright: (c) 2017 DLFC. All rights reserved. 
*
* @description: 
*
* @version: 1.0
* @date : 2017年1月12日 
* @author: Alex.Ge 
*
* @Modification  History:<br>
*  Date          Author         Version        Discription
*  2017年1月12日       Alex.Ge        1.0             <修改原因描述>
*/
package com.logistics.platform.persistence;

import java.util.List;

import org.apache.ibatis.annotations.Param;

/**
 * @name: MyCrudDao
 * @description:
 * 
 * @version 1.0
 * @author Alex.Ge
 *
 */
public interface MyCrudDao<E, T> extends BaseDao {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table fu_pay_request
	 * 
	 * @mbg.generated Sat Dec 24 14:39:59 CST 2016
	 */
	long countByExample(E example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table fu_pay_request
	 * 
	 * @mbg.generated Sat Dec 24 14:39:59 CST 2016
	 */
	int deleteByExample(E example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table fu_pay_request
	 * 
	 * @mbg.generated Sat Dec 24 14:39:59 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table fu_pay_request
	 * 
	 * @mbg.generated Sat Dec 24 14:39:59 CST 2016
	 */
	int insert(T record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table fu_pay_request
	 * 
	 * @mbg.generated Sat Dec 24 14:39:59 CST 2016
	 */
	int insertSelective(T record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table fu_pay_request
	 * 
	 * @mbg.generated Sat Dec 24 14:39:59 CST 2016
	 */
	List<T> selectByExample(E example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table fu_pay_request
	 * 
	 * @mbg.generated Sat Dec 24 14:39:59 CST 2016
	 */
	T selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table fu_pay_request
	 * 
	 * @mbg.generated Sat Dec 24 14:39:59 CST 2016
	 */
	int updateByExampleSelective(@Param("record") T record, @Param("example") E example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table fu_pay_request
	 * 
	 * @mbg.generated Sat Dec 24 14:39:59 CST 2016
	 */
	int updateByExample(@Param("record") T record, @Param("example") E example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table fu_pay_request
	 * 
	 * @mbg.generated Sat Dec 24 14:39:59 CST 2016
	 */
	int updateByPrimaryKeySelective(T record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table fu_pay_request
	 * 
	 * @mbg.generated Sat Dec 24 14:39:59 CST 2016
	 */
	int updateByPrimaryKey(T record);
}
